DROP VIEW IF EXISTS v_tcp_udp_geo;
DROP VIEW IF EXISTS v_firewall_geo;
DROP VIEW IF EXISTS v_tcp_udp;
DROP VIEW IF EXISTS v_firewall;
DROP VIEW IF EXISTS v_tcp;
DROP VIEW IF EXISTS v_udp;
DROP VIEW IF EXISTS v_icmp;
DROP VIEW IF EXISTS v_any;
DROP VIEW IF EXISTS v_other;

DROP TABLE IF EXISTS geoip;
DROP TABLE IF EXISTS log_any;
DROP TABLE IF EXISTS log_icmp;
DROP TABLE IF EXISTS log_tcp;
DROP TABLE IF EXISTS log_udp;
DROP TABLE IF EXISTS log_ip;
DROP TABLE IF EXISTS log_messages;
DROP TABLE IF EXISTS log_base;

